// Generated by CoffeeScript 1.7.1
var getactive, mysql, regsed;

mysql = require('./mysql-class');

exports.getLimit = function(callback) {
  return mysql.row_select({
    tbname: "limit",
    limit: 1
  }, callback);
};

getactive = function(id, callback) {
  return mysql.row_select({
    tbname: "active",
    where: "`id`='" + id + "'",
    limit: 1
  }, callback);
};

exports.getactive = getactive;

exports.getUsers = function(tbname, callback) {
  return mysql.row_select({
    tbname: tbname,
    limit: 5
  }, callback);
};

exports.viewed = function(id) {
  return mysql.row_update("active", "`views`=views+1", "`id`='" + id + "'", function(err, results) {
    return console.log(err, results);
  });
};

regsed = function(id) {
  return mysql.row_update("active", "`regs`=regs+1", "`id`='" + id + "'", function(err, results) {
    return console.log(err, results);
  });
};

exports.regsed = regsed;

exports.create_active = function(newtbname, callback) {
  return mysql.copy_table('regdemo', newtbname, callback);
};

exports.check_table = function(tbname, callback) {
  return mysql.check_table(tbname, callback);
};

exports.getActives = function(callback) {
  return mysql.row_select({
    tbname: "active",
    where: "",
    limit: 20,
    order: "order"
  }, callback);
};

exports.getBanner = function(callback) {
  return mysql.row_select({
    tbname: "banner",
    where: "(`stardate` >= '" + (new Date().getTime()) + "' and `enddate` <= '" + (new Date().getTime()) + "') or forever = 1",
    order: "order"
  }, callback);
};

exports.getBannertj = function(callback) {
  return mysql.row_select({
    tbname: "banner_tj",
    where: "(`stardate` >= '" + (new Date().getTime()) + "' and `enddate` <= '" + (new Date().getTime()) + "') or forever = 1",
    order: "order"
  }, callback);
};

exports.limits = function(uid, callback) {
  var sql;
  sql = "select a.* from `limit` as a left join `limit_reg` as b on a.id = b.lid where b.uid='" + uid + "' order by b.create_at desc";
  return mysql.query(sql, callback);
};

exports.checklimit = function(lid, uid, callback) {
  return mysql.row_select({
    tbname: "limit_reg",
    where: "`lid`='" + lid + "' and `uid`='" + uid + "'"
  }, callback);
};

exports.newlimit = function(data, callback) {
  return mysql.row_insert("limit_reg", data, callback);
};

exports.newactive = function(data, callback) {
  return mysql.row_insert("active", data, callback);
};

exports.checkac = function(aid, uid, callback) {
  return mysql.row_select({
    tbname: "useractive",
    where: "`aid`='" + aid + "' and `uid`='" + uid + "'",
    limit: 1
  }, callback);
};

exports.joinactive = function(aid, uid, data, callback) {
  return getactive(aid, function(err, results) {
    regsed(aid);
    return mysql.row_insert("useractive", {
      aid: aid,
      uid: uid,
      create_at: new Date()
    }, function(err, resu) {
      return mysql.row_insert("regdemo_" + results[0].ename, data, callback);
    });
  });
};

exports.joinactivenou = function(aid, data, callback) {
  return getactive(aid, function(err, results) {
    regsed(aid);
    return mysql.row_insert("regdemo_" + results[0].ename, data, callback);
  });
};

exports.getArts = function(callback) {
  return mysql.row_select({
    tbname: "art",
    limit: 20,
    order: "order"
  }, callback);
};

exports.getArt = function(id, callback) {
  return mysql.row_select({
    tbname: "art",
    where: "`id`='" + id + "'"
  }, callback);
};

exports.newart = function(data, callback) {
  return mysql.row_insert("art", data, callback);
};
