// Generated by CoffeeScript 1.7.1
var helper, mysql;

mysql = require('./mysql-class');

helper = require('../lib/helper');

exports.getmobile = function(mobile, callback) {
  return mysql.row_select({
    tbname: "user",
    where: "`mobile` = '" + mobile + "'"
  }, callback);
};

exports.usersnumber = function(callback) {
  return mysql.row_count('user', null, callback);
};

exports.login = function(mobile, password, callback) {
  return mysql.row_select({
    tbname: "user",
    where: "`mobile` = '" + mobile + "' and `password` = '" + password + "'"
  }, callback);
};

exports.getUserActive = function(id, callback) {
  var sql;
  sql = "select active.* from useractive left join active on useractive.aid = active.id where useractive.uid = " + id + " order by useractive.id desc";
  return mysql.query(sql, callback);
};

exports.getUser = function(id, callback) {
  return mysql.row_select({
    tbname: "user",
    where: "`id`='" + id + "'",
    limit: 1
  }, callback);
};

exports.updateUserInfo = function(id, data, callback) {
  data = helper.arstr(data);
  return mysql.row_update("user", data, "`id`='" + id + "'", callback);
};

exports.check = function(mobile, callback) {
  return mysql.row_select({
    tbname: "user",
    where: "`mobile`='" + mobile + "'"
  });
};

exports.reg = function(options, callback) {
  return mysql.row_insert('user', options, callback);
};
